### ISSUE TITLE
re-ranking demo

### ISSUE THREAD

**Issue by billtiger** [douzi0248/Re-ID#8]
Firstly,thank you for you sharing the nice code!
And can you provide a re-ranking demo?because after i add the re-ranking code,the result is
Rank@1:0.000000  Rank@5:0.000000 Rank@10:0.000000 mAP:0.000465

**Comment by douzi0248** [comment]
&nbsp;
  I have added the re-ranking code
 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"billtiger"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月31日(星期二) 下午2:57
 收件人:&nbsp;"douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[douzi0248/Re-ID] re-ranking demo (#8)

 

 
Firstly,thank you for you sharing the nice code!
And can you provide a re-ranking demo?because after i add the re-ranking code,the result is
Rank@1:0.000000 Rank@5:0.000000 Rank@10:0.000000 mAP:0.000465

**Comment by billtiger** [comment]
thank you,i have get it!

**Comment by David1-git** [comment]
怎么使用re-ranking代码,没有看到在哪里调用了
